name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: npm install
        run: npm install

      #- name: npm run start
        #run: npm run start

      #- name: npm run start /w filter
        #run: npm run 'start /w filter'
        
      #- name: npm run start /w errors
        #run: npm run 'start /w errors'
